<a href="https://colab.research.google.com/github/vmotta/Algebra-Linear-Python/blob/master/classificacao_multiclasse_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [0]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categorical_features = [0])
y.shape

(150,)

In [0]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [0]:
y = onehot.fit_transform(y).toarray()
y

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [0]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [0]:
X_treinamento.shape

(105, 4)

In [0]:
X_teste.shape

(45, 4)

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
neuronios_entrada = X.shape[1]
neuronios_entrada

4

In [0]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [0]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [0]:
W = {'oculta': tf.Variable(tf.random_normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_oculta, neuronios_saida]))}

In [0]:
b = {'oculta': tf.Variable(tf.random_normal([neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_saida]))}

In [0]:
xph = tf.placeholder('float', [None, neuronios_entrada])
yph = tf.placeholder('float', [None, neuronios_saida])

In [0]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

In [0]:
modelo = mlp(xph, W, b)

In [0]:
erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = modelo, labels = yph))
otimizador = tf.train.AdamOptimizer(learning_rate = 0.0001).minimize(erro)

In [0]:
batch_size = 8
batch_total = int(len(X_treinamento) / batch_size)
batch_total

13

In [0]:
X_batches = np.array_split(X_treinamento, batch_total)
X_batches

[array([[-4.16009689e-01, -1.05276654e+00,  3.64896281e-01,
          8.77547895e-04],
        [-1.73673948e-01,  3.09077525e+00, -1.28338910e+00,
         -1.05217993e+00],
        [-5.37177559e-01,  7.88807586e-01, -1.16971425e+00,
         -1.31544430e+00],
        [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
         -1.31544430e+00],
        [-1.26418478e+00, -1.31979479e-01, -1.34022653e+00,
         -1.44707648e+00],
        [-1.14301691e+00, -1.28296331e+00,  4.21733708e-01,
          6.59038469e-01],
        [ 6.74501145e-01,  9.82172869e-02,  9.90107977e-01,
          7.90670654e-01],
        [ 1.88617985e+00, -5.92373012e-01,  1.33113254e+00,
          9.22302838e-01],
        [ 7.95669016e-01,  3.28414053e-01,  7.62758269e-01,
          1.05393502e+00]]),
 array([[-1.14301691,  1.24920112, -1.34022653, -1.44707648],
        [ 0.18982966, -0.13197948,  0.59224599,  0.79067065],
        [ 1.03800476,  0.55861082,  1.10378283,  1.18556721],
        [-1.50652052,  0.0982

In [0]:
X_batches[1]

array([[-1.14301691,  1.24920112, -1.34022653, -1.44707648],
       [ 0.18982966, -0.13197948,  0.59224599,  0.79067065],
       [ 1.03800476,  0.55861082,  1.10378283,  1.18556721],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [ 1.03800476, -0.13197948,  0.8195957 ,  1.44883158],
       [-0.53717756, -0.13197948,  0.42173371,  0.3957741 ],
       [-0.29484182, -0.13197948,  0.42173371,  0.3957741 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ]])

In [0]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoca in range(3000):
        erro_medio = 0.0
        batch_total = int(len(X_treinamento) / batch_size)
        X_batches = np.array_split(X_treinamento, batch_total)
        y_batches = np.array_split(y_treinamento, batch_total)
        for i in range(batch_total):
            X_batch, y_batch = X_batches[i], y_batches[i]
            _, custo = sess.run([otimizador, erro], feed_dict = {xph: X_batch, yph: y_batch})
            erro_medio += custo / batch_total
        if epoca % 500 == 0:
            print('Época: ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))
    W_final, b_final = sess.run([W, b])

Época: 1 erro: 2.0767518190237193
Época: 501 erro: 0.2434411673591687
Época: 1001 erro: 0.11854750147232643
Época: 1501 erro: 0.09363498803801262
Época: 2001 erro: 0.08272322288785988
Época: 2501 erro: 0.07630310322229679


In [0]:
W_final

{'oculta': array([[ 0.3069872 ,  0.13064109, -0.89932626,  1.0622605 ],
        [-0.59986424, -0.7134212 ,  1.6118956 ,  1.0008155 ],
        [ 0.8087519 ,  2.516314  ,  1.0366175 , -0.32883883],
        [-0.46637127,  1.6064285 ,  2.0601325 , -2.4649198 ]],
       dtype=float32), 'saida': array([[-2.7249625 ,  2.8480437 ,  0.61928916],
        [-1.1449637 , -0.3988416 ,  2.860213  ],
        [-1.6631134 ,  0.6057659 ,  0.4764836 ],
        [ 2.9565377 ,  0.40425146, -0.6635709 ]], dtype=float32)}

In [0]:
b_final

{'oculta': array([ 0.9885877, -1.3519396,  1.5066282,  1.4147959], dtype=float32),
 'saida': array([ 0.60186386,  0.5222603 , -0.3699796 ], dtype=float32)}

In [0]:
# previsões
previsoes_teste = mlp(xph, W_final, b_final)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    r1 = sess.run(previsoes_teste, feed_dict = {xph: X_teste})
    r2 = sess.run(tf.nn.softmax(r1))
    r3 = sess.run(tf.argmax(r2, 1))

In [0]:
r1

array([[ 11.888717  ,   0.8105181 ,  -2.3286712 ],
       [ 10.682332  ,   0.8605111 ,  -2.0312812 ],
       [  8.292652  ,   0.79500705,  -1.5204263 ],
       [-17.434418  ,   4.599289  ,  14.376266  ],
       [-15.234273  ,   6.378102  ,  14.556869  ],
       [ 11.032741  ,   1.3882036 ,  -2.134895  ],
       [ -5.4996843 ,   5.333876  ,   4.6178355 ],
       [ -3.9500024 ,   4.012832  ,   1.3086301 ],
       [ -4.697706  ,   2.8414466 ,   1.5427452 ],
       [ -4.225012  ,   3.954082  ,   1.4740186 ],
       [ 15.533578  ,   1.6779418 ,  -3.101013  ],
       [ -6.9113045 ,   3.831295  ,   2.3706846 ],
       [  9.363835  ,   1.2589817 ,  -1.7600863 ],
       [ -6.4544563 ,   4.510582  ,   3.082317  ],
       [-14.946244  ,   5.8371944 ,  13.978131  ],
       [-18.049288  ,   3.9871159 ,  13.751447  ],
       [-12.623038  ,   4.7313037 ,  10.883697  ],
       [ 12.303388  ,   1.3172066 ,  -2.365997  ],
       [ -2.5058098 ,   4.463874  ,   0.91549206],
       [ -1.6594431 ,   5.36367

In [0]:
r2

array([[9.99983788e-01, 1.54451627e-05, 6.69051815e-07],
       [9.99942780e-01, 5.42515845e-05, 3.00969850e-06],
       [9.99391198e-01, 5.54051017e-04, 5.46978081e-05],
       [1.53027954e-14, 5.67398783e-05, 9.99943256e-01],
       [1.15278907e-13, 2.80469190e-04, 9.99719560e-01],
       [9.99933362e-01, 6.47741763e-05, 1.91134677e-06],
       [1.32506193e-05, 6.71725631e-01, 3.28261107e-01],
       [3.26219480e-04, 9.36968327e-01, 6.27053827e-02],
       [4.17653908e-04, 7.85288274e-01, 2.14294106e-01],
       [2.58718675e-04, 9.22493517e-01, 7.72476792e-02],
       [9.99999046e-01, 9.60667421e-07, 8.07420797e-09],
       [1.75346340e-05, 8.11611831e-01, 1.88370690e-01],
       [9.99683261e-01, 3.01973778e-04, 1.47504325e-05],
       [1.39512504e-05, 8.06619585e-01, 1.93366483e-01],
       [2.74269079e-13, 2.91279255e-04, 9.99708712e-01],
       [1.54557882e-14, 5.74619080e-05, 9.99942541e-01],
       [6.16923665e-11, 2.12386227e-03, 9.97876167e-01],
       [9.99982595e-01, 1.69338

In [0]:
r3

array([0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 1, 1, 1,
       2, 0, 0, 2, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 0, 1, 0, 0, 2, 1, 1, 2,
       1])

In [0]:
y_teste2 = np.argmax(y_teste, 1)
y_teste2

array([0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 1, 1, 1,
       2, 0, 0, 2, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 0, 2,
       1])

In [0]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, r3)
taxa_acerto

0.9555555555555556